service: lsc-file-upload-import
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

  environment:
    S3_INPUT_BUCKET_NAME: ${file(./config/config.${self:provider.stage}.json):fileUploadBucketName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:provider.environment.S3_INPUT_BUCKET_NAME}/*"

functions:
  inputBucketTrigger:
    handler: src/handler.bucketFileTrigger
    events:
      - s3:
          bucket: ${self:provider.environment.S3_INPUT_BUCKET_NAME}
          event: s3:ObjectRemoved:*

